name: 'Typing - SVG Text'
author: 'Tonal Mathew'
description: 'Text to svg in readme'

inputs:
  input-text:
    description: 'Text to be displayed as svg'
    required: true
    default: 
      - Hello, from SVG!
      - This is a dynamic SVG.

runs: 
  using: 'node16'
  main: 'dist/index.js'