name: 'Typing - Readme SVG Text'
author: 'Tonal Mathew'
description: 'Text to svg in readme'

inputs:
  INPUT_TEXT:
    description: 'Text to be displayed as svg'
    required: true
    type: string
    multiline: true
  COMMITTER_NAME:
    description: "Name of the committer"
    default: "github-actions[bot]"
    required: false
  COMMITTER_EMAIL: 
    description: "Email of the committer"
    default: "41898282+github-actions[bot]@users.noreply.github.com"
    required: false

runs: 
  using: 'node16'
  main: 'dist/index.js'