name: test run

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_TOKEN }}

    - name: Run the action
      uses: ./
      with:
        input-text: [Test text line 1, Test text line 2]

    - name: Commit and push if it changed
      run: |
        git diff
        git config --global user.email "tonalmathew.dev@gmail.com"
        git config --global user.name "Tonal Mathew"
        git commit -am "Automated README update" || exit 0
        git push
