name: test run

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  update-readme:
    steps:
    - name: Run the action
      uses: ./.github/actions/readme-typing
      with:
        input-text: 'Test text line 1, Test text line 2'
