name: test run

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
        token: ${{ secrets.GH_TOKEN }}

    - name: Run the action
      uses: ./
      with:
        input-text: |
          Test text line 1 
          Test text line 2

    - name: Commit and push if it changed
      run: |
        git diff
        git add readme-typing.svg
        git commit -am "[feat] add readme-typing.svg" || exit 0
        git push origin ${{ github.head_ref }}
