name: test run

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
        token: ${{ secrets.GH_TOKEN }}

    - name: Run the action
      uses: ./
      with:
        input-text: |
          hello, from svg typing.
          This is dyamically generated.

    - name: Commit and push if it changed
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git add readme-typing.svg
        git commit -m "[feat] update readme-typing.svg" || exit 0
        git push origin ${{ github.head_ref }}
